version: '3'
services:
  streamr:
    # Uncomment the desired architecture image
    # image: ghcr.io/alehechka/streamr:amd64
    # image: ghcr.io/alehechka/streamr:arm
    container_name: streamr
    ports:
      - 8080:8080
    volumes:
      - C:/Documents/GitHub/streamr/server/app/media:/app/media

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "59 11 * * *" --cleanup
