name: Deploy Docker Image to GHCR
on:
  push:
    branches:
      - main

env:
  IMAGE_ID: ghcr.io/${{ github.repository }}

jobs:
  build-client:
    name: Build CRA Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js (NPM)
        uses: actions/setup-node@master
        with:
          node-version: '14.x'

      - name: Cache Node Modules
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: client

      - name: Install dependencies
        run: |
          cd client
          yarn install --frozen-lockfile
        env:
          CI: true

      - name: Build
        run: |
          cd client
          yarn build
        env:
          CI: true

      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: client
          path: client/build

  build-server:
    name: Build GoLang Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Install Dependencies
        run: go get -d -v
        working-directory: server

      # - name: Run Tests
      #   run: go test -tags mock ./...
      #   working-directory: server

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -a streamr
        working-directory: server

  docker:
    name: Dockerize Application
    needs:
      - build-client
      - build-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Download Client Artifact
        uses: actions/download-artifact@main
        with:
          name: client
          path: build/client

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Install Server Dependencies
        run: go get -d -v
        working-directory: server

      - name: Build Server
        run: CGO_ENABLED=0 GOOS=linux go build -a streamr
        working-directory: server

      - name: Move Server executable
        run: mv server/streamr build/server

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build --platform linux/amd64,linux/arm/v7 --push -t ${{ env.IMAGE_ID }}:latest .
      - name: Push Image
        run: |
          docker push ${{ env.IMAGE_ID }}:latest
